config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reports
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]

  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:name, :location, :fund_partner, :install_date, :system, :technician)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Reports', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      	<li class="nav-item">
      		<%= link_to 'Reports List', reports_path, class:"nav-link" %>
      	</li>

        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'New Report', new_report_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Account', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Reports</h1>

<p>This web application lets you create, search, view, edit, and delete reports.</p>

app/views/home/index.html.erb
<h1>Reports</h1>
<br/>

<p>Welcome to Reports Application!</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Reports</title>
  </head>
  <body>
    <%= render 'home/header' %>
    
    <div class="container">
        <br/>
        <% if notice %>
            <%= render 'layouts/alerts' %>
        <% end %>

      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form class="row g-3">
  <div class="row g-3">
    <div class="field col-md-6">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="field col-md-6">
      <%= form.label :location, class: "form-label" %>
      <%= form.text_field :location, class: "form-control" %>
    </div>
  </div>
  <br/>

  <div class="row g-3">
    <div class="field col-md-6">
      <%= form.label :fund_partner, class: "form-label" %>
      <%= form.text_field :fund_partner, class: "form-control" %>
    </div>
    <div class="field col-md-6">
      <%= form.label :install_date, class: "form-label" %>
      <%= form.text_field :install_date, class: "form-control" %>
    </div>
  </div>
  <br/>

  <div class="field col-12">
    <%= form.label :system, class: "form-label" %>
    <%= form.text_field :system, class: "form-control" %>
  </div>
  <br/>

  <div class="field col-12">
    <%= form.label :technician, class: "form-label" %>
    <%= form.text_field :technician, class: "form-control" %>
  </div>
  <br/>

  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
</form>
<br/>

<% end %>

app/views/reports/edit.html.erb
<h1>Edit Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report, class:"btn btn-secondary" %>
<%= link_to 'Back', reports_path, class:"btn btn-dark" %>

app/views/reports/index.html.erb
<h1>Reports List</h1>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Fund partner</th>
      <th>Install date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.name %></td>
        <td><%= report.location %></td>
        <td><%= report.fund_partner %></td>
        <td><%= report.install_date %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path, class: "btn btn-secondary" %>

app/views/reports/new.html.erb
<h1>Create New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path, class:"btn btn-dark" %>

app/views/reports/show.html.erb
<div class="card border-dark mb-3">
  <div class="card-header">
    <%= @report.name %>
  </div>
  <div class="card-body text-dark">
    <h4 class="card-title">Location</h4>
    <p class="card-text">
      <%= @report.location %>
    </p>
    <h4 class="card-title">Funding Partner</h4>
    <p class="card-text">
      <%= @report.fund_partner %>
    </p>
    <h4 class="card-title">Installation Date</h4>
    <p class="card-text">
      <%= @report.install_date %>
    </p>
    <h4 class="card-title">System Components</h4>
    <p class="card-text">
      <%= @report.system %>
    </p>
    <h4 class="card-title">Technicians</h4>
    <p class="card-text">
      <%= @report.technician %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_report_path(@report), class: "btn btn-dark" %>
<%= link_to 'Back', reports_path, class: "btn btn-secondary" %>